import AosInit from '@/components/AosInit'
import FooterMain from '@/shared/footer.main'
import NavbarMain from '@/shared/navbar.main'
import { ThemeProvider } from 'next-themes'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider attribute='class' defaultTheme='light' enableSystem>
					<NavbarMain />
					<AosInit />
					{children}
					<FooterMain />
				</ThemeProvider>
			</body>
		</html>
	)
}
